version: "3.7"
services:

  web-app:
    build:
      context: .
    depends_on:
      - mongo
      - minio
    expose:
      - "5000"
    networks:
      net:
    environment:
      MINIO_ENDPOINT: "${MINIO_ENDPOINT:-minio.localhost}"
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY:-minioadmin}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY:-minioadmin}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web-app-minimo.rule=Host(`nuc`)"
      - "traefik.http.routers.web-app-minimo.entrypoints=web-secure"
      - "traefik.http.routers.web-app-minimo.tls=true"
    # docker run -p 49160:5000 --name minimo-web-app -d minimo/node-web-app

  mongo:
    image: mongo
    expose:
      - "27017"
    environment:
      MONGO_INITDB_DATABASE: test
    volumes:
      - mongodb-data:/data/db
    networks:
      net:
    # docker run -it -v /data/db -p 27017:27017 --name minimo-mongo -d mongo

  minio:
    image: minio/minio
    expose:
      - "9000"
    environment:
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY:-minioadmin}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY:-minioadmin}"
    entrypoint: sh
    command: -c 'mkdir -p /data/data && /usr/bin/minio ${MINIO_COMMAND:-server} /data'
    volumes:
      - ${MINIO_DATA_DIRECTORY:-minio-data}:/data
    networks:
      net:
        aliases:
          - ${MINIO_ENDPOINT:-minio.localhost}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio-minimo.rule=Host(`nuc`)"
      - "traefik.http.routers.minio-minimo.rule=PathPrefix(`/minio/`)"
      - "traefik.http.routers.minio-minimo.entrypoints=web-secure"
      - "traefik.http.routers.minio-minimo.tls=true"
    # docker run -p 9000:9000 --name minimo-minio -d minio/minio server /data

  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.2
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=web-secure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.web-secure.address=:443"
    ports:
      # The HTTP port
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      net:

networks:
  net:

volumes:
  minio-data:
  mongodb-data: