version: "3.7"
services:

  web-app:
    build:
      context: .
    depends_on:
      - mongo
      - minio
    expose:
      - "5000"
    networks:
      net:
    environment:
      HOST_NAME: "${HOST_NAME:-minimo.localhost}"
      MINIO_ADMIN_USERNAME: "${MINIO_ADMIN_USERNAME:-minioadmin}"
      MINIO_ADMIN_PASSWORD: "${MINIO_ADMIN_PASSWORD:-minioadmin}"
      MINIMO_USER_PASSWORD: "${MINIMO_USER_PASSWORD:-minimouser}"
      MINIO_REGION: "${MINIO_REGION:-}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web-app-minimo.rule=Host(`${HOST_NAME:-minimo.localhost}`)"
      - "traefik.http.routers.web-app-minimo.entrypoints=web-secure"
      - "traefik.http.routers.web-app-minimo.tls=true"
    # docker run -p 49160:5000 --name minimo-web-app -d minimo/node-web-app

  mongo:
    image: mongo
    expose:
      - "27017"
    environment:
      MONGO_INITDB_DATABASE: test
    volumes:
      - mongodb-data:/data/db
    networks:
      net:
    # docker run -it -v /data/db -p 27017:27017 --name minimo-mongo -d mongo

  minio:
    image: minio/minio
    expose:
      - "80"
    environment:
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY:-minioadmin}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY:-minioadmin}"
    entrypoint: sh
    command: -c 'mkdir -p /data/data && /usr/bin/minio ${MINIO_COMMAND:-server} --address :80 /data'
    volumes:
      - ${MINIO_DATA_DIRECTORY:-minio-data}:/data
    networks:
      net:
        aliases:
          - ${HOST_NAME:-minimo.localhost}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio-minimo.rule=Host(`${HOST_NAME:-minimo.localhost}`)"
      - "traefik.http.routers.minio-minimo.rule=PathPrefix(`/minio/`,`/data{regex:$$|/.*}`)"
      - "traefik.http.routers.minio-minimo.entrypoints=web-secure"
      - "traefik.http.routers.minio-minimo.tls=true"
      - "traefik.frontend.passHostHeader=true"
    # docker run -p 9000:9000 --name minimo-minio -d minio/minio server /data

  mc:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: sh
    command: >
      -c '
        /usr/bin/mc alias set minimo http://minio:80 ${MINIO_ADMIN_USERNAME:-minioadmin} ${MINIO_ADMIN_PASSWORD:-minioadmin};
        mc admin user add minimo minimouser ${MINIMO_USER_PASSWORD:-minimouser};
        mc admin policy add minimo readlist /dev/stdin <<<"{\"Version\": \"2012-10-17\",\"Statement\": [{\"Effect\": \"Allow\",\"Action\": [\"s3:GetBucketLocation\",\"s3:GetObject\",\"s3:ListBucket\"],\"Resource\": [\"arn:aws:s3:::*\"]}]}";
        mc admin policy set minimo readlist user=minimouser;
        '
    networks:
      net:

  reverse-proxy:
    image: traefik:v2.2
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=web-secure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.web-secure.address=:443"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      net:

networks:
  net:

volumes:
  minio-data:
  mongodb-data: