# from https://github.com/peter-evans/docker-compose-actions-workflow
name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the app
        run: HOST_NAME=localhost docker-compose up -d --build --force-recreate
      - name: Test connection to web app
        run: docker run --network host appropriate/curl -s --retry 10 --retry-connrefused --insecure https://127.0.0.1
