# from https://github.com/peter-evans/docker-compose-actions-workflow
name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the app
        run: HOST_NAME=localhost docker-compose up -d --build --force-recreate
      - name: Test connection to web app
        id: test-connection
        run: docker run --network container:minimo_reverse-proxy_1 appropriate/curl -s --retry 10 --retry-connrefused --insecure https://localhost
      - uses: nick-invision@assert-action@v1
        with:
          expected: Welcome to the minimo FAQ!
          actual: ${{ steps.test-connection.outputs.value }}
          comparison: contains
